server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.103:1111 #换成nginx的1111端口 做集群
      #server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'