server:
  port: 80

eureka:
  client: #客户端注册进eureka服务列表内
    register-with-eureka: false #表示是否将自己注册进eurekaServer默认为true
    service-url:
      defaultZone: http://localhost:7001/eureka

feign:
  hystrix:
    enabled: true